CREATE TABLE [dbo].[Asset] (
    [AssetId]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [AssetCode]             VARCHAR (50)    NULL,
    [TagCode]               VARCHAR (50)    NULL,
    [ClassCode]             VARCHAR (50)    NULL,
    [Description]           VARCHAR (255)   NULL,
    [Manufacturer]          VARCHAR (100)   NULL,
    [Model]                 VARCHAR (50)    NULL,
    [SerialNumber]          VARCHAR (50)    NULL,
    [AcquiredDate]          DATE            NULL,
    [OriginalCost]          DECIMAL (18, 2) NULL,
    [ReplacementCost]       DECIMAL (18, 2) NULL,
    [Depreciation]          DECIMAL (18, 2) NULL,
    [Location]              VARCHAR (50)    NULL,
    [SubLocation]           VARCHAR (50)    NULL,
    [Quantity]              INT             NULL,
    [EquipmentStatusXRefId] BIGINT          NOT NULL,
    [GenericLocationLevel1] VARCHAR (50)    NULL,
    [GenericLocationLevel2] VARCHAR (50)    NULL,
    [GenericLocationLevel3] VARCHAR (50)    NULL,
    [AssetNumber]           BIGINT          NOT NULL,
    CONSTRAINT [PK_Assets] PRIMARY KEY CLUSTERED ([AssetId] ASC),
    CONSTRAINT [FK_Assets_UDC] FOREIGN KEY ([EquipmentStatusXRefId]) REFERENCES [dbo].[UDC] ([XRefId])
);

