CREATE TABLE [dbo].[JobCostLedger] (
    [JobCostLedgerId]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [JobMasterId]         BIGINT          NOT NULL,
    [ContractId]          BIGINT          NOT NULL,
    [EstimatedHours]      DECIMAL (18, 2) NULL,
    [EstimatedAmount]     MONEY           NULL,
    [JobPhaseId]          BIGINT          NULL,
    [ActualHours]         DECIMAL (18, 2) NULL,
    [ActualCost]          MONEY           NULL,
    [ProjectedHours]      DECIMAL (18, 2) NULL,
    [ProjectedAmount]     MONEY           NULL,
    [CommittedHours]      DECIMAL (18, 2) NULL,
    [CommittedAmount]     MONEY           NULL,
    [Description]         VARCHAR (255)   NULL,
    [TransactionType]     VARCHAR (20)    NULL,
    [Source]              VARCHAR (100)   NULL,
    [JobCostLedgerNumber] BIGINT          NOT NULL,
    [CustomerId]          BIGINT          NULL,
    [JobCostTypeId]       BIGINT          NOT NULL,
    [SupplierId]          BIGINT          NULL,
    [PurchaseOrderId]     BIGINT          NULL,
    [InvoiceId]           BIGINT          NULL,
    [TaxAmount]           MONEY           NULL,
    CONSTRAINT [PK_JobCostDetail] PRIMARY KEY CLUSTERED ([JobCostLedgerId] ASC),
    CONSTRAINT [FK_JobCostLedger_Contract] FOREIGN KEY ([ContractId]) REFERENCES [dbo].[Contract] ([ContractId]),
    CONSTRAINT [FK_JobCostLedger_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_JobCostLedger_JobCostType] FOREIGN KEY ([JobCostTypeId]) REFERENCES [dbo].[JobCostType] ([JobCostTypeId]),
    CONSTRAINT [FK_JobCostLedger_JobMaster] FOREIGN KEY ([JobMasterId]) REFERENCES [dbo].[JobMaster] ([JobMasterId]),
    CONSTRAINT [FK_JobCostLedger_JobPhase] FOREIGN KEY ([JobPhaseId]) REFERENCES [dbo].[JobPhase] ([JobPhaseId])
);

