CREATE TABLE [dbo].[SalesOrderDetail] (
    [SalesOrderDetailId]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderId]                BIGINT          NOT NULL,
    [ItemId]                      BIGINT          NOT NULL,
    [Description]                 VARCHAR (255)   NULL,
    [Quantity]                    BIGINT          NULL,
    [Amount]                      DECIMAL (18, 4) NOT NULL,
    [UnitOfMeasure]               VARCHAR (25)    NULL,
    [UnitPrice]                   DECIMAL (18, 4) NULL,
    [BuyerId]                     BIGINT          NULL,
    [ScheduledShipDate]           DATETIME        NULL,
    [PromisedDate]                DATETIME        NULL,
    [GrossWeight]                 DECIMAL (18, 4) NULL,
    [GrossWeightUnitOfMeasure]    VARCHAR (25)    NULL,
    [ShippedDate]                 DATETIME        NULL,
    [AccountId]                   BIGINT          NULL,
    [LotSerial]                   VARCHAR (50)    NULL,
    [BusUnit]                     VARCHAR (10)    NULL,
    [LineNumber]                  BIGINT          NULL,
    [CompanyNumber]               VARCHAR (10)    NULL,
    [CarrierId]                   BIGINT          NULL,
    [InvoiceDate]                 DATETIME        NULL,
    [GLDate]                      DATETIME        NULL,
    [Location]                    VARCHAR (50)    NULL,
    [QuantityShipped]             BIGINT          NULL,
    [QuantityOpen]                BIGINT          NULL,
    [AmountOpen]                  MONEY           NULL,
    [PaymentTerms]                VARCHAR (20)    NULL,
    [PaymentInstrument]           VARCHAR (50)    NULL,
    [UnitVolume]                  DECIMAL (18, 4) NULL,
    [UnitVolumeUnitOfMeasurement] VARCHAR (50)    NULL,
    [PurchaseOrderDetailId]       BIGINT          NULL,
    [PurchaseOrderId]             BIGINT          NULL,
    [PickListId]                  BIGINT          NULL,
    [PickListDetailId]            BIGINT          NULL,
    [SalesOrderDetailNumber]      BIGINT          NULL,
    CONSTRAINT [PK_SalesOrderDetail] PRIMARY KEY CLUSTERED ([SalesOrderDetailId] ASC),
    CONSTRAINT [FK_SalesOrderDetail_ItemMaster] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[ItemMaster] ([ItemId]),
    CONSTRAINT [FK_SalesOrderDetail_SalesOrder] FOREIGN KEY ([SalesOrderId]) REFERENCES [dbo].[SalesOrder] ([SalesOrderId])
);

