//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Millennium.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public long BudgetId { get; set; }
        public Nullable<decimal> BudgetHours { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> RangeId { get; set; }
    
        public virtual BudgetRange BudgetRange { get; set; }
        public virtual ChartOfAcct ChartOfAcct { get; set; }
    }
}
