//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumERP.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetSnapShot
    {
        public long BudgetId { get; set; }
        public Nullable<decimal> BudgetHours { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> RangeId { get; set; }
        public Nullable<decimal> ProjectedHours { get; set; }
        public Nullable<decimal> ProjectedAmount { get; set; }
        public Nullable<decimal> OpenPurchaseOrderAmount { get; set; }
        public string Comments { get; set; }
    }
}
