//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumERP.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> LoginEmail { get; set; }
        public string Email1 { get; set; }
        public long AddressId { get; set; }
    }
}
