//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumERP.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicesDetail
    {
        public long InvoiceDetailId { get; set; }
        public long InvoiceId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> PurchaseOrderLineId { get; set; }
        public Nullable<long> SalesOrderDetailId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    }
}
