//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumERP.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public long PurchaseOrderDetailId { get; set; }
        public long PurchaseOrderId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> OrderedQuantity { get; set; }
        public long ItemId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<long> VendorAddressId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
        public Nullable<int> RemainingQuantity { get; set; }
    }
}
