//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillenniumERP.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public long ShipmentId { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public long BillToAddressId { get; set; }
        public long CarrierId { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<decimal> BillableWeight { get; set; }
        public Nullable<decimal> Duty { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CodAmount { get; set; }
        public long ShippedFromId { get; set; }
        public Nullable<long> ShippedToAddressId { get; set; }
        public Nullable<long> PurchaseOrderId { get; set; }
        public Nullable<long> VendorInvoiceId { get; set; }
        public Nullable<decimal> VendorShippingCost { get; set; }
        public Nullable<decimal> VendorHandlingCost { get; set; }
    }
}
