//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPDataCore.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long ItemId { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Remarks { get; set; }
        public string UOM { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<long> DistributionAccountId { get; set; }
        public Nullable<long> ReceivingAccountId { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
