// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class AccountBalance
    {
        public long AccountBalanceId { get; set; }
        public string AccountBalanceType { get; set; }
        public decimal? Amount { get; set; }
        public decimal? Hours { get; set; }
        public int FiscalYear { get; set; }
        public int FiscalPeriod { get; set; }
        public long AccountId { get; set; }

        public virtual ChartOfAccount Account { get; set; }

    }
}