// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class AccountReceivableDetail
    {
        public long AccountReceivableDetailId { get; set; }
        public long InvoiceId { get; set; }
        public long InvoiceDetailId { get; set; }
        public long AccountReceivableId { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal? Amount { get; set; }
        public decimal? AmountReceived { get; set; }
        public long? PurchaseOrderDetailId { get; set; }
        public long? SalesOrderDetailId { get; set; }
        public long? ItemId { get; set; }
        public long AccountReceivableDetailNumber { get; set; }
        public long? PurchaseOrderId { get; set; }
        public long? CustomerId { get; set; }
        public long? SupplierId { get; set; }
        public long? QuantityDelivered { get; set; }
        public string Comment { get; set; }
        public string TypeOfPayment { get; set; }

        public virtual AccountReceivable AccountReceivable { get; set; }

    }
}