// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class BudgetNote
    {
        public long BudgetNoteId { get; set; }
        public long BudgetId { get; set; }
        public string Note { get; set; }
        public DateTime Create { get; set; }
        public long BudgetNoteNumber { get; set; }

        public virtual Budget Budget { get; set; }

    }
}