// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class ContractItem
    {
        public long ContractItemId { get; set; }
        public long ContractId { get; set; }
        public string Wbs { get; set; }
        public string ItemDescription { get; set; }
        public string UnitOfMeasure { get; set; }
        public int? Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? ExtendedCost { get; set; }
        public decimal? Fees { get; set; }
        public string ContractType { get; set; }
        public string PaymentMethod { get; set; }
        public int? DurationHours { get; set; }
        public DateTime? EstimatedStartDate { get; set; }
        public DateTime? EstimatedEndDate { get; set; }
        public long ContractItemNumber { get; set; }

        public virtual Contract Contract { get; set; }

    }
}