// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class ContractInvoice
    {
        public long ContractInvoiceId { get; set; }
        public long ContractId { get; set; }
        public long InvoiceId { get; set; }
        public long ContractInvoiceNumber { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Invoice Invoice { get; set; }

    }
}