// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class Contract
    {
        public Contract()
        {
            AccountPayable = new HashSet<AccountPayable>();
            ContractItem = new HashSet<ContractItem>();
            ServiceInformation = new HashSet<ServiceInformation>();
        }

        public long ContractId { get; set; }
        public long? CustomerId { get; set; }
        public long? ServiceTypeXrefId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal? Cost { get; set; }
        public decimal? RemainingBalance { get; set; }
        public string Title { get; set; }
        public long ContractNumber { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Udc ServiceTypeXref { get; set; }
        public virtual ICollection<AccountPayable> AccountPayable { get; set; }
        public virtual ICollection<ContractItem> ContractItem { get; set; }
        public virtual ICollection<ServiceInformation> ServiceInformation { get; set; }

    }
}