// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class Customer
    {
        public Customer()
        {
            AccountReceivable = new HashSet<AccountReceivable>();
            AccountReceivableFee = new HashSet<AccountReceivableFee>();
            AccountReceivableInterest = new HashSet<AccountReceivableInterest>();
            Contract = new HashSet<Contract>();
            CustomerClaim = new HashSet<CustomerClaim>();
            CustomerLedger = new HashSet<CustomerLedger>();
            Invoice = new HashSet<Invoice>();
            Poquote = new HashSet<Poquote>();
            SalesOrder = new HashSet<SalesOrder>();
            ScheduleEvent = new HashSet<ScheduleEvent>();
            ServiceInformation = new HashSet<ServiceInformation>();
            Shipment = new HashSet<Shipment>();
        }

        public long CustomerId { get; set; }
        public long AddressId { get; set; }
        public long? PrimaryShippedToLocationAddressId { get; set; }
        public long? PrimaryEmailId { get; set; }
        public long? PrimaryPhoneId { get; set; }
        public long? MailingLocationAddressId { get; set; }
        public long? PrimaryBillingLocationAddressId { get; set; }
        public string TaxIdentification { get; set; }
        public long? CustomerNumber { get; set; }

        public virtual AddressBook Address { get; set; }
        public virtual ICollection<AccountReceivable> AccountReceivable { get; set; }
        public virtual ICollection<AccountReceivableFee> AccountReceivableFee { get; set; }
        public virtual ICollection<AccountReceivableInterest> AccountReceivableInterest { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual ICollection<CustomerClaim> CustomerClaim { get; set; }
        public virtual ICollection<CustomerLedger> CustomerLedger { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Poquote> Poquote { get; set; }
        public virtual ICollection<SalesOrder> SalesOrder { get; set; }
        public virtual ICollection<ScheduleEvent> ScheduleEvent { get; set; }
        public virtual ICollection<ServiceInformation> ServiceInformation { get; set; }
        public virtual ICollection<Shipment> Shipment { get; set; }

    }
}