// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class EmailEntity
    {
        public long EmailId { get; set; }
        public string Password { get; set; }
        public bool? LoginEmail { get; set; }
        public string Email { get; set; }
        public long EmailEntityNumber { get; set; }
        public long AddressId { get; set; }

        public virtual AddressBook Address { get; set; }

    }
}