// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class EmployeePosition
    {
        public long PositionCodeId { get; set; }
        public string PositionCode { get; set; }
        public long CompanyId { get; set; }
        public string Description { get; set; }
        public long PositionCodeNumber { get; set; }

        public virtual Company Company { get; set; }

    }
}