// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class JobCostType
    {
        public JobCostType()
        {
            JobCostLedger = new HashSet<JobCostLedger>();
        }

        public long JobCostTypeId { get; set; }
        public string CostCode { get; set; }
        public string Description { get; set; }
        public string Account { get; set; }
        public long JobCostTypeNumber { get; set; }

        public virtual ICollection<JobCostLedger> JobCostLedger { get; set; }

    }
}