// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class JobCostLedger
    {
        public long JobCostLedgerId { get; set; }
        public long JobMasterId { get; set; }
        public long ContractId { get; set; }
        public decimal? EstimatedHours { get; set; }
        public decimal? EstimatedAmount { get; set; }
        public long? JobPhaseId { get; set; }
        public decimal? ActualHours { get; set; }
        public decimal? ActualCost { get; set; }
        public decimal? ProjectedHours { get; set; }
        public decimal? ProjectedAmount { get; set; }
        public decimal? CommittedHours { get; set; }
        public decimal? CommittedAmount { get; set; }
        public string Description { get; set; }
        public string TransactionType { get; set; }
        public string Source { get; set; }
        public long JobCostLedgerNumber { get; set; }
        public long? CustomerId { get; set; }
        public long JobCostTypeId { get; set; }
        public long? SupplierId { get; set; }
        public long? PurchaseOrderId { get; set; }
        public long? InvoiceId { get; set; }
        public decimal? TaxAmount { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual JobCostType JobCostType { get; set; }
        public virtual JobMaster JobMaster { get; set; }
        public virtual JobPhase JobPhase { get; set; }

    }
}