// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class JobChangeOrder
    {
        public long JobChangeOrderId { get; set; }
        public long JobMasterId { get; set; }
        public long ContractId { get; set; }
        public long ContractItemId { get; set; }
        public string Description { get; set; }
        public long? InvoiceId { get; set; }
        public long? AcctRecId { get; set; }
        public long? CustomerId { get; set; }
        public decimal ChangeAmount { get; set; }
        public decimal? EstimatedAmount { get; set; }
        public long JobChangeOrderNumber { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ContractItem ContractItem { get; set; }
        public virtual JobMaster JobMaster { get; set; }

    }
}