// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class JobMaster
    {
        public JobMaster()
        {
            JobChangeOrder = new HashSet<JobChangeOrder>();
            JobCostLedger = new HashSet<JobCostLedger>();
            JobPhase = new HashSet<JobPhase>();
        }

        public long JobMasterId { get; set; }
        public long ContractId { get; set; }
        public string JobDescription { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public long? ProjectManagerId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? CompleteDate { get; set; }
        public decimal? TotalCommittedAmount { get; set; }
        public decimal? ActualAmount { get; set; }
        public decimal? ActualHours { get; set; }
        public decimal? EstimatedAmount { get; set; }
        public decimal? EstimatedHours { get; set; }
        public decimal? ProjectedAmount { get; set; }
        public decimal? ProjectHours { get; set; }
        public decimal? RemainingCommittedAmount { get; set; }
        public decimal? RetainageAmount { get; set; }
        public long JobMasterNumber { get; set; }
        public long CustomerId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<JobChangeOrder> JobChangeOrder { get; set; }
        public virtual ICollection<JobCostLedger> JobCostLedger { get; set; }
        public virtual ICollection<JobPhase> JobPhase { get; set; }

    }
}