// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class JobPhase
    {
        public JobPhase()
        {
            JobCostLedger = new HashSet<JobCostLedger>();
        }

        public long JobPhaseId { get; set; }
        public int PhaseGroup { get; set; }
        public long JobMasterId { get; set; }
        public string Phase { get; set; }
        public long ContractId { get; set; }
        public long JobPhaseNumber { get; set; }
        public long JobCostTypeId { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual JobMaster JobMaster { get; set; }
        public virtual ICollection<JobCostLedger> JobCostLedger { get; set; }

    }
}