// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class NetTerms
    {
        public long NetTermId { get; set; }
        public string NetTerms1 { get; set; }
        public decimal? DiscountPercent { get; set; }

    }
}