// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class ProjectManager
    {
        public long ProjectManagerId { get; set; }
        public long AddressBookId { get; set; }

    }
}