// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            AccountPayable = new HashSet<AccountPayable>();
            PurchaseOrderDetail = new HashSet<PurchaseOrderDetail>();
        }

        public long PurchaseOrderId { get; set; }
        public string DocType { get; set; }
        public string PaymentTerms { get; set; }
        public string Remark { get; set; }
        public DateTime? Gldate { get; set; }
        public long AccountId { get; set; }
        public long SupplierId { get; set; }
        public long? ContractId { get; set; }
        public long? PoquoteId { get; set; }
        public string Description { get; set; }
        public string Ponumber { get; set; }
        public string TakenBy { get; set; }
        public long? BuyerId { get; set; }
        public DateTime? RequestedDate { get; set; }
        public DateTime? PromisedDeliveredDate { get; set; }
        public decimal? Tax { get; set; }
        public DateTime? TransactionDate { get; set; }
        public decimal? AmountPaid { get; set; }
        public string ShippedToName { get; set; }
        public string ShippedToAddress1 { get; set; }
        public string ShippedToAddress2 { get; set; }
        public string ShippedToCity { get; set; }
        public string ShippedToZipcode { get; set; }
        public string ShippedToState { get; set; }
        public string TaxCode1 { get; set; }
        public string TaxCode2 { get; set; }
        public long PurchaseOrderNumber { get; set; }
        public decimal? Amount { get; set; }

        public virtual ChartOfAccount Account { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<AccountPayable> AccountPayable { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }

    }
}