// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class ServiceInformationInvoice
    {
        public long ServiceInformationInvoiceId { get; set; }
        public long InvoiceId { get; set; }
        public long ServiceId { get; set; }
        public long ServiceInformationInvoiceNumber { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual ServiceInformation Service { get; set; }

    }
}