// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class TaxRatesByCode
    {
        public TaxRatesByCode()
        {
            Invoice = new HashSet<Invoice>();
        }

        public long TaxRatesByCodeId { get; set; }
        public string TaxCode { get; set; }
        public decimal? TaxRate { get; set; }
        public string State { get; set; }
        public long TaxRatesByCodeNumber { get; set; }

        public virtual ICollection<Invoice> Invoice { get; set; }

    }
}