// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class TimeAndAttendanceSetup
    {
        public long TimeAndAttendanceSetupId { get; set; }
        public string TimeZone { get; set; }
        public bool? DaylightSavings { get; set; }
        public int? Offset { get; set; }
        public long TimeAndAttendanceSetupNumber { get; set; }

    }
}