// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace lssWebApi2.EntityFramework
{
    public partial class Udc
    {
        public Udc()
        {
            AccountReceivable = new HashSet<AccountReceivable>();
            Asset = new HashSet<Asset>();
            Carrier = new HashSet<Carrier>();
            Contract = new HashSet<Contract>();
            CustomerClaimClassificationXref = new HashSet<CustomerClaim>();
            CustomerClaimGroupIdXref = new HashSet<CustomerClaim>();
            EmployeeEmploymentStatusXref = new HashSet<Employee>();
            EmployeeJobTitleXref = new HashSet<Employee>();
            LocationAddress = new HashSet<LocationAddress>();
            ProjectManagementTask = new HashSet<ProjectManagementTask>();
            ServiceInformation = new HashSet<ServiceInformation>();
            Supervisor = new HashSet<Supervisor>();
            TimeAndAttendancePunchIn = new HashSet<TimeAndAttendancePunchIn>();
        }

        public long XrefId { get; set; }
        public string ProductCode { get; set; }
        public string KeyCode { get; set; }
        public string Value { get; set; }
        public long UdcNumber { get; set; }

        public virtual ICollection<AccountReceivable> AccountReceivable { get; set; }
        public virtual ICollection<Asset> Asset { get; set; }
        public virtual ICollection<Carrier> Carrier { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual ICollection<CustomerClaim> CustomerClaimClassificationXref { get; set; }
        public virtual ICollection<CustomerClaim> CustomerClaimGroupIdXref { get; set; }
        public virtual ICollection<Employee> EmployeeEmploymentStatusXref { get; set; }
        public virtual ICollection<Employee> EmployeeJobTitleXref { get; set; }
        public virtual ICollection<LocationAddress> LocationAddress { get; set; }
        public virtual ICollection<ProjectManagementTask> ProjectManagementTask { get; set; }
        public virtual ICollection<ServiceInformation> ServiceInformation { get; set; }
        public virtual ICollection<Supervisor> Supervisor { get; set; }
        public virtual ICollection<TimeAndAttendancePunchIn> TimeAndAttendancePunchIn { get; set; }

    }
}